export const HOME_CASUAL = 'home_casual'; // 首页轮播图
export const HOME_NAV = 'home_nav'; // 首页导航
export const HOME_SHOP_LIST = 'home_shop_list'; // 首页商品列表
export const RECOMMEND_SHOP_LIST = 'recommend_shop_list'; // 推荐商品列表
export const SRARCH_GOODS = 'search_goods'; //
export const USER_INFO = 'user_info'; // 同步用户信息
export const RESET_USER_INFO = 'reset_user_info'; // 清空用户信息
export const CART_GOODS_LIST = 'cart_goods_list'; //购物车数据
export const ADD_GOODS_COUNT = 'add_goods_count'; //增加购物车单个数据
export const REDUCE_GOODS_LIST = 'reduce_goods_count'; //减少购物车单个数据
export const SELECTED_ALL_GOODS = 'selected_all_goods'; //是否选中所有商品
export const SELECTED_SINGER_GOODS = 'selected_singer_goods'; //单个商品选中和取消
export const DEL_SINGER_GOODS = 'del_singer_goods'; //单个商品删除
